#!/bin/sh

ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

hwclock --systohc

echo "en_AU.UTF-8 UTF-8" >>/etc/locale.gen
locale-gen

printf "Enter the hostname: " && read hostname
echo "$hostname" >/etc/hostname

echo "127.0.0.1     localhost" >>/etc/hosts
echo "::1           localhost" >>/etc/hosts
echo "127.0.1.1     $hostname.localdomain   $hostname" >>/etc/hosts

echo "Set the root password"
passwd

printf "Enter the username: " && read username
useradd -m $username
echo "Enter your $username's password: "
passwd $username

echo "Adding $username into some important groups"
usermod -aG wheel,audio,video,optical,storage $username

echo "Replacing sudo with doas"
pacman -S opendoas which dash --noconfirm
echo "permit nopass $username as root" >/etc/doas.conf
ln -s $(which doas) /bin/sudo
ln -s $(which dash) /bin/sh

echo "[multilib]" >>/etc/pacman.conf
echo "Include = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf

pacman -Syyu

pacman -S networkmanager efibootmgr dosfstools os-prober mtools --noconfirm

mkdir /efi
lsblk
printf "Enter the boot partition (only name, ex: sda1) : " && read bootDrive
mount /dev/$bootDrive /efi

bootctl --esp-path=/efi --boot-path=/boot install

mkdir /etc/pacman.d/hooks -p
touch /etc/pacman.d/hooks/95-systemd-boot.hook

echo "[Trigger]" >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "Type = Package" >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "Operation = Upgrade" >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "Target = systemd" >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "[Action]" >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "Description = Gracefully upgrading systemd-boot..." >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "When = PostTransaction" >>/etc/pacman.d/hooks/95-systemd-boot.hook
echo "Exec = /usr/bin/systemctl restart systemd-boot-update.service" >>/etc/pacman.d/hooks/95-systemd-boot.hook

systemctl enable NetworkManager
systemctl start NetworkManager

pacman -S git fakeroot --noconfirm

pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
pacman-key --lsign-key 3056513887B78AEB
pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

echo "[chaotic-aur]" >>/etc/pacman.conf
echo "Include = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf

pacman -Syyu

chown $username:$username ./postpost
mv ./postpost /home/$username
echo "run 'cd && ./postpost'"
su $username
